<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CorporateServiceRequest</name>
   <tag></tag>
   <elementGuidId>5ef8d9ad-ec33-404c-b816-d6921ffd594f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='id-770e2a5d-395e-4324-b253-2591e0cd2646-15-subjectid8-subjectid.fieldControl-subject-tree-dropdown-icon-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-770e2a5d-395e-4324-b253-2591e0cd2646-15-subjectid8-subjectid.fieldControl-subject-tree-dropdown-icon-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Group collapsed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>subjectid.fieldControl-subject-tree-dropdown-icon-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>symbolFont Arrow-symbol pa-a pa-no pa-iy pa-an pa-am pa-xo </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-770e2a5d-395e-4324-b253-2591e0cd2646-15-subjectid8-subjectid.fieldControl-subject-tree-dropdown-icon-1&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id-770e2a5d-395e-4324-b253-2591e0cd2646-15-subjectid8-subjectid.fieldControl-subject-tree-dropdown-icon-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='id-770e2a5d-395e-4324-b253-2591e0cd2646-15-subjectid8-subjectid.fieldControl-subject-tree-dropdown-1']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/ul/li[2]/span</value>
   </webElementXpaths>
</WebElementEntity>
