<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Txt_CustomerNameSearch</name>
   <tag></tag>
   <elementGuidId>913ce1ae-39a1-440c-8ebf-2b0d23c95e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-a1bbfb2d-0d75-49da-b05e-ca99030c5c5a-7-vrp_customername6-vrp_customername.fieldControl-text-box-text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
